server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: product-route
          uri: http://localhost:8082
          predicates:
            - name: Path
              args:
                pattern: /products/**
        - id: cart-route
          uri: http://localhost:8084
          predicates:
            - name: Path
              args:
                pattern: /cart/**
        - id: sales-route
          uri: http://localhost:8085
          predicates:
            - name: Path
              args:
                pattern: /sales/**

management:
  endpoints:
    web:
      exposure:
        include: gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka