server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: cart-route
          uri: http://localhost:8084
          predicates:
            - Path=/cart/**


        - id: product-route
          uri: http://localhost:8082
          predicates:
            - Path=/products/**


        - id: sales-route
          uri: http://localhost:8085
          predicates:
            - Path=/sales/**


management:
  endpoints:
    web:
      exposure:
        include: gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka