server:
  port: 8087

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/inventory_db
    username: root
    password: ${DB_PASSWORD}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
      show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: inventory-group-v5
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: true
        spring.json.value.default.type: "com.electrotienda.inventory_service.event.ProductCreatedEvent"
        spring.json.type.mapping: "sale:com.electrotienda.inventory_service.event.SaleCreatedEvent, product:com.electrotienda.inventory_service.event.ProductCreatedEvent"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka